#ifndef ABILITY_EXPANSION_H
#define ABILITY_EXPANSION_H

#include "battle_events.h"

extern "C" BattleEventHandlerTableEntry* EventAddAromaVeil(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddFlowerVeil(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddCheekPouch(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddProtean(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddFurCoat(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddMagician(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddBulletProof(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddCompetitive(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddStrongJaw(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddRefrigerate(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSweetVeil(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddStanceChange(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGaleWings(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddMegaLauncher(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGrassPelt(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSymbiosis(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddToughClaws(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPixilate(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGooey(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddAerilate(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddParentalBond(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddDarkAura(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddFairyAura(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddAuraBreak(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPrimordialSea(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddDesolateLand(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddDeltaStream(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddStamina(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddEmergencyExit(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddEmergencyExit(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddWaterCompaction(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddMerciless(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddShieldsDown(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddStakeout(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddWaterBubble(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSteelworker(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddBerserk(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSlushRush(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddLiquidVoice(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddTriage(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGalvanize(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSchooling(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSurgeSurfer(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddShieldsDown(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddDisguise(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddBattleBond(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPowerConstruct(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddQueenlyMagesty(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddInnardsOut(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddDancer(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddBattery(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddFluffy(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddQueenlyMagesty(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSoulHeart(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGooey(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddReceiver(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddReceiver(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddBeastBoost(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddElectricSurge(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPsychicSurge(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddMistySurge(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGrassySurge(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPrismArmor(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddNeuroforce(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddIntrepidSword(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddDauntlessShield(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddProtean(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddBallFetch(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddCottonDown(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPropellerTail(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddMirrorArmor(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGulpMissile(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPropellerTail(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSteamEngine(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPunkRock(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSandSpit(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddIceScales(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddRipen(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddIceFace(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPowerSpot(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddMimicry(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddScreenCleaner(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSteelySpirit(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPerishBody(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddWanderingSpirit(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGorillaTactics(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddNeutralizingGas(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPastelVeil(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddHungerSwitch(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddQuickDraw(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddUnseenFist(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddCuriousMedicine(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddTransistor(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddDragonsMaw(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddChillingNeigh(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGrimNeigh(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddAsOne(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddAsOne(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSeedSower(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddThermalExchange(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddAngerShell(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPurifyingSalt(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddWellBakedBody(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddWindRider(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGuardDog(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddRockyPayload(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddWindPower(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddZeroToHero(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddCommander(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddElectromorphosis(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddProtosynthesis(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddQuarkDrive(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddGoodAsGold(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddVesselOfRuin(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSwordOfRuin(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddTabletsOfRuin(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddBeadsOfRuin(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddOrichalcumPulse(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddHadronEngine(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddOpportunist(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddCudChew(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSharpness(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSupremeOverlord(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddCostar(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddToxicDebris(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddQueenlyMagesty(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddEarthEater(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddMyceliumMight(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddHospitality(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddMindsEye(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddEmbodyAspectTeal(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddEmbodyAspectHearthflame(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddEmbodyAspectWellspring(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddEmbodyAspectCornerstorne(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddToxicChain(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddSupersweetSyrup(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddTeraShift(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddTeraShell(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddTeraformZero(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry* EventAddPoisonPuppeteer(u32 * handlerAmount);

//Natural Cure - can't find after battle status heal
//Soundproof - update Heal Bell in Move Expansion
//Sap Sipper - update Aromatherapy in Move Expansion
extern "C" BattleEventHandlerTableEntry * EventAddObliviousUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddOwnTempoUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddInnerFocusUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddScrappyUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddRattledUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddLightningRodUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddKeenEyeUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddTraceUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddSoundproofUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddNormalizeUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddFriskUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddOvercoatUpdated(u32 * handlerAmount);
extern "C" BattleEventHandlerTableEntry * EventAddPranksterUpdated(u32 * handlerAmount);

extern "C" void HandlerIgnoreIntimidate(BattleEventItem* item, ServerFlow* serverFlow, u32 pokemonSlot, u32* work);

#endif // ABILITY_EXPANSION_H

