.thumb

#include "settings.h"

#if REMOVE_LOCATION_LIMIT

FULL_COPY_ZoneData_GetPlaceNameID_0x14:
    nop
    nop
    nop
    .size FULL_COPY_ZoneData_GetPlaceNameID_0x14, . - FULL_COPY_ZoneData_GetPlaceNameID_0x14

FULL_COPY_SetPkmnMetLocation_0x6:
    nop
    nop
    nop
    .size FULL_COPY_SetPkmnMetLocation_0x6, . - FULL_COPY_SetPkmnMetLocation_0x6

FULL_COPY_LoadZoneBanner_0x10:
    nop
    nop
    nop
    .size FULL_COPY_LoadZoneBanner_0x10, . - FULL_COPY_LoadZoneBanner_0x10

#endif // REMOVE_LOCATION_LIMIT